# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Trd_Common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Trd_Common.proto',
  package='Trd_Common',
  syntax='proto2',
  serialized_pb=_b('\n\x10Trd_Common.proto\x12\nTrd_Common\"\xa5\x01\n\x05Order\x12$\n\x07trdSide\x18\x01 \x02(\x0e\x32\x13.Trd_Common.TrdSide\x12(\n\torderType\x18\x02 \x02(\x0e\x32\x15.Trd_Common.OrderType\x12\x0f\n\x07orderID\x18\x03 \x02(\x04\x12\x11\n\torderIDEx\x18\x04 \x02(\t\x12\x0c\n\x04\x63ode\x18\x05 \x02(\t\x12\x0b\n\x03qty\x18\x06 \x02(\x01\x12\r\n\x05price\x18\x07 \x01(\x01*.\n\x06TrdEnv\x12\x13\n\x0fTrdEnv_Simulate\x10\x00\x12\x0f\n\x0bTrdEnv_Real\x10\x01*\xb9\x01\n\tTrdMarket\x12\x15\n\x11TrdMarket_Unknown\x10\x00\x12\x16\n\x12TrdMarket_HK_Stock\x10\x01\x12\x16\n\x12TrdMarket_US_Stock\x10\x15\x12\x17\n\x13TrdMarket_US_Option\x10\x16\x12\x18\n\x14TrdMarket_CNSH_Stock\x10\x1f\x12\x18\n\x14TrdMarket_CNSZ_Stock\x10 \x12\x18\n\x14TrdMarket_HKCC_Stock\x10)*A\n\x07TrdSide\x12\x13\n\x0fTrdSide_Unknown\x10\x00\x12\x0f\n\x0bTrdSide_Buy\x10\x01\x12\x10\n\x0cTrdSide_Sell\x10\x02*\xb2\x01\n\tOrderType\x12\x15\n\x11OrderType_Unknown\x10\x00\x12\x14\n\x10OrderType_Normal\x10\x01\x12\x13\n\x0fOrderType_Limit\x10\x03\x12\x15\n\x11OrderType_Auction\x10\x06\x12\x1a\n\x16OrderType_AuctionLimit\x10\x07\x12\x1a\n\x16OrderType_SpecialLimit\x10\x08\x12\x14\n\x10OrderType_Market\x10\x02')
)

_TRDENV = _descriptor.EnumDescriptor(
  name='TrdEnv',
  full_name='Trd_Common.TrdEnv',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TrdEnv_Simulate', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TrdEnv_Real', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=200,
  serialized_end=246,
)
_sym_db.RegisterEnumDescriptor(_TRDENV)

TrdEnv = enum_type_wrapper.EnumTypeWrapper(_TRDENV)
_TRDMARKET = _descriptor.EnumDescriptor(
  name='TrdMarket',
  full_name='Trd_Common.TrdMarket',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TrdMarket_Unknown', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TrdMarket_HK_Stock', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TrdMarket_US_Stock', index=2, number=21,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TrdMarket_US_Option', index=3, number=22,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TrdMarket_CNSH_Stock', index=4, number=31,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TrdMarket_CNSZ_Stock', index=5, number=32,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TrdMarket_HKCC_Stock', index=6, number=41,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=249,
  serialized_end=434,
)
_sym_db.RegisterEnumDescriptor(_TRDMARKET)

TrdMarket = enum_type_wrapper.EnumTypeWrapper(_TRDMARKET)
_TRDSIDE = _descriptor.EnumDescriptor(
  name='TrdSide',
  full_name='Trd_Common.TrdSide',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TrdSide_Unknown', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TrdSide_Buy', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TrdSide_Sell', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=436,
  serialized_end=501,
)
_sym_db.RegisterEnumDescriptor(_TRDSIDE)

TrdSide = enum_type_wrapper.EnumTypeWrapper(_TRDSIDE)
_ORDERTYPE = _descriptor.EnumDescriptor(
  name='OrderType',
  full_name='Trd_Common.OrderType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OrderType_Unknown', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OrderType_Normal', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OrderType_Limit', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OrderType_Auction', index=3, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OrderType_AuctionLimit', index=4, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OrderType_SpecialLimit', index=5, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OrderType_Market', index=6, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=504,
  serialized_end=682,
)
_sym_db.RegisterEnumDescriptor(_ORDERTYPE)

OrderType = enum_type_wrapper.EnumTypeWrapper(_ORDERTYPE)
TrdEnv_Simulate = 0
TrdEnv_Real = 1
TrdMarket_Unknown = 0
TrdMarket_HK_Stock = 1
TrdMarket_US_Stock = 21
TrdMarket_US_Option = 22
TrdMarket_CNSH_Stock = 31
TrdMarket_CNSZ_Stock = 32
TrdMarket_HKCC_Stock = 41
TrdSide_Unknown = 0
TrdSide_Buy = 1
TrdSide_Sell = 2
OrderType_Unknown = 0
OrderType_Normal = 1
OrderType_Limit = 3
OrderType_Auction = 6
OrderType_AuctionLimit = 7
OrderType_SpecialLimit = 8
OrderType_Market = 2



_ORDER = _descriptor.Descriptor(
  name='Order',
  full_name='Trd_Common.Order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trdSide', full_name='Trd_Common.Order.trdSide', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderType', full_name='Trd_Common.Order.orderType', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderID', full_name='Trd_Common.Order.orderID', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderIDEx', full_name='Trd_Common.Order.orderIDEx', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='Trd_Common.Order.code', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qty', full_name='Trd_Common.Order.qty', index=5,
      number=6, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='Trd_Common.Order.price', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=198,
)

_ORDER.fields_by_name['trdSide'].enum_type = _TRDSIDE
_ORDER.fields_by_name['orderType'].enum_type = _ORDERTYPE
DESCRIPTOR.message_types_by_name['Order'] = _ORDER
DESCRIPTOR.enum_types_by_name['TrdEnv'] = _TRDENV
DESCRIPTOR.enum_types_by_name['TrdMarket'] = _TRDMARKET
DESCRIPTOR.enum_types_by_name['TrdSide'] = _TRDSIDE
DESCRIPTOR.enum_types_by_name['OrderType'] = _ORDERTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), dict(
  DESCRIPTOR = _ORDER,
  __module__ = 'Trd_Common_pb2'
  # @@protoc_insertion_point(class_scope:Trd_Common.Order)
  ))
_sym_db.RegisterMessage(Order)


# @@protoc_insertion_point(module_scope)
